import type { EditionDefinition, ProductSlug } from "./types";

const tier = (
  productSlug: ProductSlug,
  slug: EditionDefinition["slug"],
  input: Omit<EditionDefinition, "productSlug" | "slug" | "name"> & { readonly name?: string },
): EditionDefinition => ({
  productSlug,
  slug,
  name: input.name ?? `${productSlug === "msp" ? "MSP" : productSlug === "erp" ? "ERP" : productSlug === "ai" ? "AI" : productSlug[0].toUpperCase() + productSlug.slice(1)} ${slug.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ")}`,
  ...input,
});

export const EDITIONS: readonly EditionDefinition[] = [
  tier("crm", "essentials", {
    offerKey: "crm.essentials",
    billingUnit: "user",
    summary: "The customer record, pipeline, tasks, and finance foundation a growing team needs.",
    bestFor: "Small teams replacing spreadsheets or a disconnected entry CRM.",
    includes: ["Companies, contacts, and sites", "Activities, tasks, and opportunities", "Core pipeline and imports", "Finance Core", "Standard reporting"],
    limits: ["One core pipeline", "Standard automation and AI limits"],
    trialEligible: true,
  }),
  tier("crm", "professional", {
    offerKey: "crm.professional",
    billingUnit: "user",
    summary: "A complete selling system with automation, forecasting, proposals, and enhanced AI.",
    bestFor: "Teams with a repeatable sales motion and multiple routes to revenue.",
    includes: ["Everything in Essentials", "Multiple pipelines", "Email and calendar synchronization", "Cadences and sales automation", "Enrichment, proposals, and forecasting", "Advanced reporting and enhanced AI"],
    limits: ["Professional API and automation limits"],
    trialEligible: true,
  }),
  tier("crm", "enterprise", {
    offerKey: "crm.enterprise",
    billingUnit: "user",
    summary: "Governed CRM for complex organizations, integrations, and higher-volume operations.",
    bestFor: "Multi-team organizations with audit, policy, integration, and reporting requirements.",
    includes: ["Everything in Professional", "APIs and webhooks", "Advanced permissions and governance", "Audit controls", "Enterprise reporting and higher limits", "Enterprise AI"],
    limits: ["Contracted enterprise limits"],
    trialEligible: true,
  }),
  tier("msp", "essentials", {
    offerKey: "msp.essentials",
    billingUnit: "technician",
    summary: "PSA, projects, customer records, and service operations for a focused MSP.",
    bestFor: "Small providers standardizing tickets, projects, time, and client work.",
    includes: ["PSA and ticket operations", "Projects and time", "Sidekick CRM and Finance Core", "Core service reporting", "Standard Sidekick AI"],
    limits: ["Edition-defined managed endpoint limit", "Core automation"],
    trialEligible: true,
  }),
  tier("msp", "professional", {
    offerKey: "msp.professional",
    billingUnit: "technician",
    summary: "Unified PSA and RMM with automation, client portal, and stronger operational intelligence.",
    bestFor: "Established MSPs managing recurring service across many customers and endpoints.",
    includes: ["Everything in Essentials", "RMM, alerts, and assets", "Client portal", "Service automation", "Internal operations", "Enhanced finance and AI"],
    limits: ["Professional endpoint and automation limits"],
    trialEligible: true,
  }),
  tier("msp", "enterprise", {
    offerKey: "msp.enterprise",
    billingUnit: "technician",
    summary: "Enterprise-grade service delivery, governance, integrations, and unlimited RMM.",
    bestFor: "Large or multi-entity providers with custom controls and integration requirements.",
    includes: ["Everything in Professional", "Advanced proposals and bookings", "API and webhooks", "Governance and audit", "Unlimited RMM", "Enterprise finance and AI"],
    limits: ["Contracted service limits"],
    trialEligible: true,
  }),
  tier("rentals", "essentials", {
    offerKey: "rentals.essentials",
    billingUnit: "organization",
    summary: "Core rental availability, reservations, commerce, projects, and customer operations.",
    bestFor: "Independent rental businesses moving beyond paper and disconnected calendars.",
    includes: ["Rental catalogue and availability", "Quotes and reservations", "Commerce and POS", "Projects, proposals, and bookings", "HR, CRM, and Sidekick AI"],
    limits: ["Single-location operating model", "Core warehouse workflows"],
    trialEligible: true,
  }),
  tier("rentals", "professional", {
    offerKey: "rentals.professional",
    billingUnit: "organization",
    summary: "Multi-location rental operations with portal, warehouse, dispatch, and enhanced intelligence.",
    bestFor: "Growing fleets coordinating inventory, delivery, inspections, and customer self-service.",
    includes: ["Everything in Essentials", "Customer portal", "Warehouse and dispatch", "Multi-location operations", "Enhanced finance", "Enhanced AI"],
    limits: ["Professional telemetry and integration limits"],
    trialEligible: true,
  }),
  tier("rentals", "enterprise", {
    offerKey: "rentals.enterprise",
    billingUnit: "organization",
    summary: "Governed fleet and rental operations with telemetry, APIs, and enterprise controls.",
    bestFor: "Regional and national operators with complex fleets, entities, and integrations.",
    includes: ["Everything in Professional", "Enterprise rental operations", "Telemetry", "API and webhooks", "Governance", "Enterprise finance and AI"],
    limits: ["Contracted fleet and integration limits"],
    trialEligible: true,
  }),
  tier("commerce", "essentials", {
    offerKey: "commerce.essentials", billingUnit: "organization",
    summary: "A connected catalogue, online store, POS, inventory, and order foundation.", bestFor: "Small sellers unifying in-person and online operations for the first time.",
    includes: ["Products, variants, and collections", "Online storefront and checkout", "Point of sale", "Core inventory and order management", "Customer records and standard reporting"], limits: ["Essentials channel, location, and automation limits"], trialEligible: true,
  }),
  tier("commerce", "professional", {
    offerKey: "commerce.professional", billingUnit: "organization",
    summary: "Multi-channel selling with deeper inventory, promotions, fulfilment, and automation.", bestFor: "Growing sellers coordinating locations, channels, staff, and higher order volume.",
    includes: ["Everything in Essentials", "Multiple locations and price lists", "Promotions, gift cards, and customer groups", "Advanced inventory and fulfilment", "Returns, exchanges, and enhanced reporting"], limits: ["Professional location, order, and automation limits"], trialEligible: true,
  }),
  tier("commerce", "enterprise", {
    offerKey: "commerce.enterprise", billingUnit: "organization",
    summary: "Governed commerce for complex catalogues, entities, integrations, and scale.", bestFor: "Multi-entity and high-volume operators with custom controls and fulfilment networks.",
    includes: ["Everything in Professional", "Advanced markets and catalogue governance", "Enterprise inventory and order orchestration", "API, webhooks, and integration controls", "Audit, permissions, and enterprise analytics"], limits: ["Contracted channel, order, integration, and retention limits"], trialEligible: true,
  }),
  tier("appointments", "essentials", {
    offerKey: "appointments.essentials", billingUnit: "location",
    summary: "Online booking, services, staff calendars, reminders, and customer history for one location.", bestFor: "Independent service businesses moving off paper calendars or basic booking links.",
    includes: ["Service catalogue and durations", "Staff and resource calendars", "Customer self-booking", "Confirmations and reminders", "CRM-connected client history"], limits: ["Essentials location, staff, and monthly booking limits"], trialEligible: true,
  }),
  tier("appointments", "professional", {
    offerKey: "appointments.professional", billingUnit: "location",
    summary: "A complete service-day system with deposits, waitlists, memberships, and automation.", bestFor: "Busy teams coordinating multiple staff, rooms, policies, and repeat customers.",
    includes: ["Everything in Essentials", "Deposits and cancellation policies", "Waitlists and schedule-fill automation", "Packages, memberships, and recurring visits", "Advanced reminders, intake, and reporting"], limits: ["Professional staff, workflow, and monthly booking limits"], trialEligible: true,
  }),
  tier("appointments", "enterprise", {
    offerKey: "appointments.enterprise", billingUnit: "location",
    summary: "Multi-location appointment operations with central governance and integrated workflows.", bestFor: "Franchises, groups, and regulated operators with shared services and local teams.",
    includes: ["Everything in Professional", "Multi-location services and availability", "Central policy and brand controls", "Enterprise permissions, audit, and reporting", "API, webhooks, and custom integrations"], limits: ["Contracted location, booking, integration, and retention limits"], trialEligible: true,
  }),
  tier("sites", "essentials", {
    offerKey: "sites.essentials", billingUnit: "published site",
    summary: "A professional connected website with structured pages, forms, hosting, and SEO.", bestFor: "Small businesses launching a credible web presence tied to real customer workflows.",
    includes: ["Responsive page builder and themes", "Secure hosting and custom domain", "CRM-connected forms", "SEO metadata and redirects", "Core analytics and publishing controls"], limits: ["Essentials page, editor, form, and traffic limits"], trialEligible: true,
  }),
  tier("sites", "professional", {
    offerKey: "sites.professional", billingUnit: "published site",
    summary: "Conversion-focused sites with richer content, campaigns, booking, and commerce connections.", bestFor: "Growing teams publishing frequently and measuring multiple customer journeys.",
    includes: ["Everything in Essentials", "Advanced sections and reusable content", "Campaign and attribution context", "Appointments and Commerce connections", "Enhanced analytics, forms, and automation"], limits: ["Professional editor, form, traffic, and automation limits"], trialEligible: true,
  }),
  tier("sites", "enterprise", {
    offerKey: "sites.enterprise", billingUnit: "published site",
    summary: "Governed multi-site publishing with integration, workflow, and enterprise controls.", bestFor: "Multi-brand, multi-location, and regulated organizations managing web operations at scale.",
    includes: ["Everything in Professional", "Multiple sites and governed design systems", "Publishing approvals and advanced permissions", "API, webhooks, and integration controls", "Enterprise analytics, audit, and higher limits"], limits: ["Contracted site, traffic, integration, and retention limits"], trialEligible: true,
  }),
  tier("voice", "business", {
    name: "Voice Business",
    offerKey: "voice.business",
    billingUnit: "user",
    summary: "Complete business calling for people who work at a desk, on mobile, or across both.",
    bestFor: "Businesses replacing consumer phone apps or an aging office phone system.",
    includes: ["Business numbers and porting", "Desktop and mobile calling", "Voicemail, recording, and transcription", "Hours, routing, queues, and ring groups", "Optional Poly and Yealink phones"],
    limits: ["Calling regions, usage, and number inventory follow the published service terms"],
    trialEligible: false,
  }),
  tier("voice", "contact-center", {
    name: "Voice Contact Centre",
    offerKey: "voice.contact-center",
    billingUnit: "agent",
    summary: "Queue-led customer calling with supervision, service controls, and performance visibility.",
    bestFor: "Sales, service, dispatch, and support teams handling structured inbound or outbound volume.",
    includes: ["Everything in Business Voice", "Advanced queues and skills-based routing", "Supervisor views and live controls", "Call recording, quality, and analytics", "CRM context and accountable follow-up"],
    limits: ["Agent, recording-retention, and analytics limits follow the published service terms"],
    trialEligible: false,
  }),
  tier("voice", "ai-receptionist", {
    name: "Voice AI Reception",
    offerKey: "voice.ai-receptionist",
    billingUnit: "number",
    summary: "A governed AI receptionist that can answer, route, capture intent, and book the next step.",
    bestFor: "Businesses that cannot afford to leave routine inbound calls unanswered.",
    includes: ["Natural-language greeting and intent capture", "Knowledge-guided answers", "Routing and human handoff", "Appointment and lead capture", "Transcript and outcome history"],
    limits: ["Voice AI usage is governed separately from general Sidekick AI Agent credits"],
    trialEligible: false,
  }),
  tier("payments", "processing", {
    name: "Payments Processing",
    offerKey: "payments.processing",
    billingUnit: "merchant account",
    summary: "In-person and online processing connected to the customer, order, invoice, and settlement record.",
    bestFor: "Businesses that want visible payment hardware and operational reconciliation in the same platform.",
    includes: ["Merchant onboarding", "Online and in-person acceptance", "Payment links and invoices", "Refunds, disputes, payouts, and reconciliation", "Optional supported terminal hardware"],
    limits: ["Processing approval, transaction pricing, supported rails, and hardware availability vary by country"],
    trialEligible: false,
  }),
  tier("erp", "full-user", {
    name: "ERP Full User",
    offerKey: "erp.full-user",
    billingUnit: "user",
    summary: "Full operational and financial access across accounting, procurement, inventory, projects, and reporting.",
    bestFor: "Finance, operations, purchasing, warehouse, project, and management users who run core workflows.",
    includes: ["General ledger, receivables, and payables", "Purchasing, receipts, and vendor bills", "Products, inventory, warehouses, and valuation", "Projects, time, expenses, and profitability", "Financial and operational reporting"],
    limits: ["Advanced governance, entities, and integrations follow the purchased organization package"],
    trialEligible: true,
  }),
  tier("erp", "team-user", {
    name: "ERP Team User",
    offerKey: "erp.team-user",
    billingUnit: "user",
    summary: "Focused participation for approvals, time, expenses, tasks, and employee self-service.",
    bestFor: "Team members who contribute to ERP workflows without administering finance or operations.",
    includes: ["Time and expense entry", "Assigned approvals and tasks", "Project participation", "Employee self-service", "Role-appropriate records and reporting"],
    limits: ["Does not include full accounting, procurement, warehouse, or configuration access"],
    trialEligible: true,
  }),
  tier("protect", "workstation", {
    name: "Protect Workstation",
    offerKey: "protect.workstation",
    billingUnit: "device",
    summary: "Policy-managed protection and recovery for employee workstations.",
    bestFor: "Windows and macOS endpoints that need monitored backup, policy, and recoverability.",
    includes: ["Device policy and enrollment", "Scheduled protected workloads", "Alerting and operational review", "File and device recovery workflows", "Coverage evidence in Sidekick"],
    limits: ["Storage, retention, and workload support follow the published protection policy"],
    trialEligible: false,
  }),
  tier("protect", "server", {
    name: "Protect Server",
    offerKey: "protect.server",
    billingUnit: "server",
    summary: "Monitored backup and recovery readiness for critical server workloads.",
    bestFor: "Physical and virtual servers where recovery evidence and escalation matter.",
    includes: ["Server workload policies", "Backup health and failure alerts", "Recovery-point visibility", "Restore request and escalation flow", "Operational history and reporting"],
    limits: ["Platform, storage, retention, and recovery options follow the published server policy"],
    trialEligible: false,
  }),
  tier("protect", "cloud-user", {
    name: "Protect Cloud User",
    offerKey: "protect.cloud-user",
    billingUnit: "user",
    summary: "User-scoped protection for supported cloud productivity data.",
    bestFor: "Organizations protecting employee mail, files, and collaboration records beyond native retention.",
    includes: ["User enrollment and coverage", "Scheduled cloud backup", "Search and recovery workflows", "Coverage exceptions and alerts", "Audit-ready restore history"],
    limits: ["Supported cloud services, storage, and retention follow the published protection policy"],
    trialEligible: false,
  }),
  tier("ai", "agent", {
    name: "Sidekick AI Agent",
    offerKey: "ai.agent",
    billingUnit: "agent",
    summary: "A configured agent with an explicit role, approved tools, governance, and human handoff.",
    bestFor: "Teams automating a repeatable cross-product workflow while keeping actions reviewable.",
    includes: ["Agent role and instructions", "Approved Sidekick tools", "Permission-aware execution", "Audit trail and human handoff", "Usage and outcome visibility"],
    limits: ["Agent credits are purchased and metered separately from embedded edition AI"],
    trialEligible: true,
  }),
  tier("ai", "credits-10000", {
    name: "10,000 AI Agent Credits",
    offerKey: "ai.credits.10000",
    billingUnit: "credit pack",
    summary: "A transparent usage pack for separately configured Sidekick AI Agents.",
    bestFor: "Organizations adding predictable agent capacity without changing product editions.",
    includes: ["10,000 versioned credits", "Usage attributed by agent and action", "Consumption history", "Low-balance visibility", "No impact on Voice AI usage"],
    limits: ["Credits apply only to configured Sidekick AI Agents and follow the published consumption schedule"],
    trialEligible: false,
  }),
] as const;

export const getProductEditions = (productSlug: ProductSlug) =>
  EDITIONS.filter((edition) => edition.productSlug === productSlug);
