import type { ProductDefinition, ProductSlug } from "./types";

const product = (
  definition: Omit<ProductDefinition, "miniNav" | "slices"> & {
    readonly slices: ProductDefinition["slices"];
  },
): ProductDefinition => ({
  ...definition,
  miniNav: [
    { label: "Overview", href: `/products/${definition.slug}` },
    { label: "Features", href: `/products/${definition.slug}#features` },
    { label: "Industries", href: `/products/${definition.slug}#industries` },
    ...(definition.pricingOfferKeys.length > 0 ? [{ label: "Plans", href: `/products/${definition.slug}/editions` }] : []),
    { label: "Pricing", href: `/pricing#${definition.slug}` },
  ],
});

const media = (slug: ProductSlug, kind: ProductDefinition["media"]["kind"], alt: string, direction: string) => ({
  kind,
  src: `/images/products/${slug}/hero.webp`,
  alt,
  direction,
});

export const PRODUCTS: readonly ProductDefinition[] = [
  product({
    slug: "crm",
    name: "Sidekick CRM",
    category: "Customer growth",
    tagline: "Know every customer. Move every opportunity.",
    hero: {
      eyebrow: "Sidekick CRM",
      title: "A CRM that remembers the business around the deal.",
      body: "Bring companies, contacts, sites, conversations, opportunities, proposals, tasks, and finance context into one dependable customer record.",
    },
    seo: { title: "Sidekick CRM | Connected customer and sales management", description: "Run customer records, pipelines, proposals, forecasting, automation, and Sidekick AI from one connected CRM." },
    outcomes: ["A complete customer history", "A sales process the whole team can follow", "Fewer handoffs between sales and operations"],
    featureGroups: [
      { title: "A durable customer record", description: "Keep the relationship intact from first conversation through delivery and renewal.", features: ["Companies, contacts, and sites", "Activities, notes, tasks, and timelines", "Imports, duplicate controls, and data quality", "Shared records across Sidekick products"] },
      { title: "A selling system with momentum", description: "Turn pipeline discipline into the next useful action.", features: ["Multiple pipelines and stage controls", "Email and calendar synchronization", "Cadences, automation, and enrichment", "Proposals, forecasting, and advanced reports"] },
    ],
    workflows: [
      { title: "From new lead to prepared conversation", description: "Sidekick enriches the account, collects recent activity, and puts the right next step in front of the seller.", steps: ["Capture and match the lead", "Enrich the company record", "Assign the opportunity", "Prepare a context-aware follow-up"] },
      { title: "From proposal to delivery", description: "Accepted work keeps its customer, pricing, commitments, and operational handoff together.", steps: ["Build the proposal", "Route approvals", "Record acceptance", "Open the delivery workflow"] },
    ],
    relevantIndustries: ["professional-services", "real-estate", "staffing-and-recruiting", "wholesale-distribution"],
    faqs: [
      { question: "Can we import our current CRM?", answer: "Yes. Sidekick supports structured imports, duplicate review, and staged data-quality checks." },
      { question: "Is Sidekick AI included?", answer: "Embedded AI is included according to edition limits. Separately configured AI Agents and their usage are purchased independently." },
    ],
    pricingOfferKeys: ["crm.essentials", "crm.professional", "crm.enterprise"],
    cta: { label: "Start a 30-day CRM trial", href: "/checkout?offer=crm.essentials", trialEligible: true },
    media: media("crm", "product-ui", "Sidekick CRM customer record and opportunity workspace", "Layer real customer, pipeline, and activity UI in an editorial desktop composition."),
    slices: [{ kind: "hero", theme: "navy", id: "crm-hero" }, { kind: "workflow", theme: "paper", id: "crm-record" }, { kind: "feature-ledger", theme: "white", id: "crm-features" }, { kind: "edition-comparison", theme: "paper", id: "crm-editions" }, { kind: "ai-layer", theme: "blue", id: "crm-ai" }, { kind: "faq", theme: "white", id: "crm-faq" }, { kind: "conversion", theme: "navy", id: "crm-cta" }],
  }),
  product({
    slug: "voice",
    name: "Sidekick Voice",
    category: "Communications",
    tagline: "Business calling with real phones and real help.",
    hero: { eyebrow: "Sidekick Voice", title: "Put a proper business phone on every desk that needs one.", body: "Choose Poly and Yealink phones, keep or select your numbers, build call flows, and give every user a modern desktop and mobile calling experience." },
    seo: { title: "Sidekick Voice | Business phone service with Poly and Yealink", description: "Order business calling, numbers, porting, call queues, AI reception, and real Poly or Yealink desk phones in one activation journey." },
    outcomes: ["Professional calling at the desk or away", "Numbers and porting handled in one order", "Call context connected to customer records"],
    featureGroups: [
      { title: "Calling that fits the office", description: "Use a physical phone, Sidekick Desktop, or mobile without splitting the experience.", features: ["Poly and Yealink desk phones", "Desktop and mobile calling", "Voicemail, recording, and transcription", "Queues, routing, hours, and receptionist flows"] },
      { title: "Activation without guesswork", description: "Configure the business details a phone company actually needs before service starts.", features: ["New number search by area code", "Number porting and authorization", "Emergency service addresses", "Users, seats, queues, shipping, and device assignment"] },
    ],
    workflows: [
      { title: "A new location goes live", description: "Select local numbers, map emergency addresses, choose phones, and follow every activation step.", steps: ["Add the service location", "Choose or port numbers", "Design the call flow", "Assign and ship phones"] },
      { title: "A call becomes customer work", description: "Incoming calls resolve the customer, show recent context, and preserve useful follow-up.", steps: ["Identify the caller", "Route to the right person", "Capture notes or transcription", "Create the follow-up in Sidekick"] },
    ],
    relevantIndustries: ["law-firms", "medical-clinics", "home-services", "managed-service-providers"],
    faqs: [
      { question: "Do you sell desk phones?", answer: "Yes. Sidekick offers compatible Poly and Yealink desk, cordless, and conference phones at verified retail MSRP." },
      { question: "Can we keep our existing phone numbers?", answer: "Yes. The activation wizard supports number porting, authorization, documents, and trackable port status." },
    ],
    pricingOfferKeys: ["voice.business", "voice.contact-center", "voice.ai-receptionist"],
    cta: { label: "Configure Sidekick Voice", href: "/checkout?offer=voice.business", trialEligible: false },
    media: media("voice", "hardware", "Poly and Yealink business phones showing the Sidekick calling experience", "Lead with production hardware photography and fully rendered Sidekick screens, never CSS overlays."),
    slices: [{ kind: "hero", theme: "navy", id: "voice-hero" }, { kind: "hardware-stage", theme: "white", id: "voice-phones" }, { kind: "workflow", theme: "paper", id: "voice-activation" }, { kind: "editorial-split", theme: "navy", id: "voice-calling" }, { kind: "feature-ledger", theme: "white", id: "voice-features" }, { kind: "faq", theme: "paper", id: "voice-faq" }, { kind: "conversion", theme: "blue", id: "voice-cta" }],
  }),
  product({
    slug: "payments",
    name: "Sidekick Payments",
    category: "Money and commerce",
    tagline: "Take payment wherever the work happens.",
    hero: { eyebrow: "Sidekick Payments", title: "The terminal is part of the platform, not an afterthought.", body: "Accept in-person and online payments, order the right terminal, connect invoices and orders, and reconcile money without leaving Sidekick." },
    seo: { title: "Sidekick Payments | Terminals and connected payment processing", description: "Accept in-person and online payments with Sidekick-branded terminals, merchant onboarding, unified orders, refunds, and reconciliation." },
    outcomes: ["Hardware customers can see and understand", "One payment history across channels", "Less manual reconciliation"],
    featureGroups: [
      { title: "In-person hardware, clearly offered", description: "Choose countertop, handheld, mobile, or self-service hardware by country and workflow.", features: ["Touchscreen payment terminals", "Mobile readers", "Countertop and handheld modes", "Accessories, docks, cases, and connectivity"] },
      { title: "Processing connected to the record", description: "Keep the money beside the invoice, order, booking, or customer that created it.", features: ["Online and in-person processing", "Payment links and invoices", "POS and Commerce connection", "Refunds, disputes, payouts, and reconciliation"] },
    ],
    workflows: [
      { title: "From merchant application to first payment", description: "Complete business onboarding, select hardware, follow approval, and activate the terminal.", steps: ["Enter business and ownership details", "Describe processing needs", "Choose and ship terminals", "Complete approval and activation"] },
      { title: "One order, one settlement trail", description: "Sidekick connects the sale, payment, refund, and payout in one operational history.", steps: ["Create the order", "Collect payment", "Reconcile settlement", "Handle refund or dispute"] },
    ],
    relevantIndustries: ["retail", "restaurants-and-food-service", "beauty-salons-and-spas", "equipment-rental"],
    faqs: [
      { question: "Can we buy physical payment terminals?", answer: "Yes. Country-compatible terminals and accessories are sold at verified retail MSRP and configured during ordering." },
      { question: "Is there a monthly platform fee?", answer: "Sidekick Payments has no platform subscription or setup fee at launch. Processing and hardware charges still apply." },
    ],
    pricingOfferKeys: ["payments.processing", "payments.terminals"],
    cta: { label: "Set up Sidekick Payments", href: "/checkout?offer=payments.processing", trialEligible: false },
    media: media("payments", "hardware", "Sidekick payment terminals showing checkout, tipping, and receipt screens", "Use real supported terminal forms with complete generated Sidekick screens and clean studio lighting."),
    slices: [{ kind: "hero", theme: "navy", id: "payments-hero" }, { kind: "hardware-stage", theme: "paper", id: "payments-terminals" }, { kind: "workflow", theme: "white", id: "payments-merchant" }, { kind: "feature-ledger", theme: "navy", id: "payments-features" }, { kind: "faq", theme: "white", id: "payments-faq" }, { kind: "conversion", theme: "blue", id: "payments-cta" }],
  }),
  product({
    slug: "msp",
    name: "Sidekick MSP",
    category: "Service operations",
    tagline: "Run the service desk and the business behind it.",
    hero: { eyebrow: "Sidekick MSP", title: "One operating system for the MSP, not another tool beside it.", body: "Connect PSA, RMM, tickets, assets, projects, contracts, billing, customer records, and AI-assisted service work." },
    seo: { title: "Sidekick MSP | Connected PSA, RMM, service desk, and billing", description: "Operate tickets, projects, assets, RMM, automation, contracts, portal, billing, and Sidekick AI in one MSP platform." },
    outcomes: ["One service record from alert to invoice", "Technicians see customer and asset context", "Owners can run delivery and margin together"],
    featureGroups: [
      { title: "Service delivery with context", description: "Turn requests and signals into accountable work.", features: ["Tickets, queues, SLAs, and requesters", "Projects, time, and dispatch", "Assets, alerts, and RMM", "Automation and technician workflows"] },
      { title: "The MSP business around the ticket", description: "Keep contracts, customer communication, approvals, and finance connected.", features: ["CRM and customer sites", "Agreements, service catalogue, and orders", "Client portal and approvals", "Billing, reporting, and Sidekick AI"] },
    ],
    workflows: [
      { title: "Alert to resolved service record", description: "An endpoint signal opens the right customer context and guides triage through resolution.", steps: ["Receive and correlate the alert", "Resolve customer and asset", "Run or dispatch remediation", "Document and bill the work"] },
      { title: "Order to onboarding", description: "A sold service becomes a trackable delivery plan instead of a handoff email.", steps: ["Accept the service order", "Open onboarding tasks", "Provision entitled services", "Confirm client readiness"] },
    ],
    relevantIndustries: ["managed-service-providers", "it-service-providers", "internal-service-desks", "technology-and-saas"],
    faqs: [
      { question: "Is RMM included?", answer: "RMM begins in Professional. Enterprise adds unlimited RMM and advanced governance according to the published edition." },
      { question: "Is pricing per endpoint?", answer: "Sidekick MSP is priced per technician, with endpoint limits and capabilities defined by the selected edition." },
    ],
    pricingOfferKeys: ["msp.essentials", "msp.professional", "msp.enterprise"],
    cta: { label: "Start a 30-day MSP trial", href: "/checkout?offer=msp.essentials", trialEligible: true },
    media: media("msp", "product-ui", "Sidekick MSP service desk showing tickets, assets, alerts, and customer context", "Create a dense but readable technician workspace grounded in real service operations."),
    slices: [{ kind: "hero", theme: "navy", id: "msp-hero" }, { kind: "workflow", theme: "paper", id: "msp-alert" }, { kind: "media-stage", theme: "white", id: "msp-service" }, { kind: "edition-comparison", theme: "navy", id: "msp-editions" }, { kind: "ai-layer", theme: "blue", id: "msp-ai" }, { kind: "faq", theme: "white", id: "msp-faq" }, { kind: "conversion", theme: "paper", id: "msp-cta" }],
  }),
  product({
    slug: "rentals",
    name: "Sidekick Rentals",
    category: "Rental operations",
    tagline: "Know what is available, where it is, and what happens next.",
    hero: { eyebrow: "Sidekick Rentals", title: "Run the fleet from first quote to final inspection.", body: "Connect availability, reservations, serial assets, pricing, warehouse work, dispatch, delivery, maintenance, returns, and finance." },
    seo: { title: "Sidekick Rentals | Rental inventory, reservations, dispatch, and fleet operations", description: "Manage rental availability, quotes, reservations, assets, dispatch, inspections, maintenance, returns, and accounting in one platform." },
    outcomes: ["Reliable availability across locations", "A complete history for every serialized asset", "Faster turns between return and the next rental"],
    featureGroups: [
      { title: "Availability customers can trust", description: "Commit the right asset without overbooking or hiding maintenance conflicts.", features: ["Products, combinations, and serialized assets", "Availability and rate controls", "Quotes, reservations, and extensions", "Customer portal and online catalogue"] },
      { title: "The work behind the reservation", description: "Coordinate the yard, warehouse, drivers, technicians, and finance team.", features: ["Staging, dispatch, delivery, and pickup", "Inspections, damage, maintenance, and returns", "Multi-location transfers and telemetry", "Revenue recognition and asset valuation"] },
    ],
    workflows: [
      { title: "Quote the right equipment now", description: "Sidekick checks products, combinations, location, dates, and rate rules before the team commits.", steps: ["Capture the need", "Check availability", "Build the quote", "Reserve the chosen assets"] },
      { title: "Return, inspect, and turn", description: "The return records condition, charges, maintenance needs, and next availability.", steps: ["Check in the asset", "Complete inspection", "Record damage or service", "Release it for the next reservation"] },
    ],
    relevantIndustries: ["equipment-rental", "construction", "oil-and-gas", "agribusiness"],
    faqs: [
      { question: "Can Sidekick track serialized equipment?", answer: "Yes. Individual assets retain reservations, scans, inspections, maintenance, valuation, and location history." },
      { question: "Does it support multiple locations?", answer: "Professional adds multi-location warehouse and dispatch workflows. Enterprise adds deeper telemetry, governance, and integration." },
    ],
    pricingOfferKeys: ["rentals.essentials", "rentals.professional", "rentals.enterprise"],
    cta: { label: "Start a 30-day Rentals trial", href: "/checkout?offer=rentals.essentials", trialEligible: true },
    media: media("rentals", "product-ui", "Sidekick Rentals availability board with serialized fleet and dispatch status", "Combine a real availability timeline with field photography and serialized asset detail."),
    slices: [{ kind: "hero", theme: "navy", id: "rentals-hero" }, { kind: "media-stage", theme: "paper", id: "rentals-availability" }, { kind: "workflow", theme: "white", id: "rentals-turn" }, { kind: "feature-ledger", theme: "navy", id: "rentals-depth" }, { kind: "edition-comparison", theme: "paper", id: "rentals-editions" }, { kind: "faq", theme: "white", id: "rentals-faq" }, { kind: "conversion", theme: "blue", id: "rentals-cta" }],
  }),
  product({
    slug: "erp",
    name: "Sidekick ERP",
    category: "Business operations",
    tagline: "Finance and operations on the same record.",
    hero: { eyebrow: "Sidekick ERP", title: "See the operational reason behind every financial number.", body: "Run accounting, purchasing, inventory, warehouse, projects, expenses, people operations, and reporting without separating them from customers and work." },
    seo: { title: "Sidekick ERP | Connected finance, inventory, purchasing, and operations", description: "Connect finance, purchasing, inventory, warehouse, projects, expenses, people operations, and reporting to the work that drives them." },
    outcomes: ["Financials connected to real operations", "Fewer duplicate entries between teams", "A clearer path from transaction to source record"],
    featureGroups: [
      { title: "Financial control", description: "Keep billing, collections, purchasing, expenses, and reporting on an auditable trail.", features: ["General ledger and financial reporting", "Receivables, payables, and collections", "Purchasing and vendor workflows", "Expenses, approvals, and audit history"] },
      { title: "Operational depth", description: "Connect stock, projects, people, and fulfilment to the customer and financial record.", features: ["Products, inventory, and warehouses", "Orders, fulfilment, and returns", "Projects, time, and profitability", "Employees, approvals, and multi-entity controls"] },
    ],
    workflows: [
      { title: "Purchase to stocked inventory", description: "Demand becomes an approved purchase, receipt, valuation, and available quantity.", steps: ["Identify demand", "Approve the purchase", "Receive and inspect", "Update inventory and finance"] },
      { title: "Work to financial result", description: "Sidekick connects time, materials, revenue, and margin back to the project and customer.", steps: ["Open the work", "Capture cost and time", "Invoice the customer", "Review profitability"] },
    ],
    relevantIndustries: ["manufacturing", "wholesale-distribution", "multi-entity-operators", "accountants-and-bookkeepers"],
    faqs: [
      { question: "Who needs a Full User?", answer: "Full Users run operational and financial workflows. Team Users handle lighter approval, time, expense, and self-service tasks." },
      { question: "Does ERP replace Sidekick CRM?", answer: "No. They share the same customer and business context; each product adds purpose-built workflows without duplicating the record." },
    ],
    pricingOfferKeys: ["erp.full-user", "erp.team-user"],
    cta: { label: "Start a 30-day ERP trial", href: "/checkout?offer=erp.full-user", trialEligible: true },
    media: media("erp", "product-ui", "Sidekick ERP operational finance dashboard linking transactions to customers and work", "Use an editorial financial ledger paired with inventory and project context, not generic charts."),
    slices: [{ kind: "hero", theme: "navy", id: "erp-hero" }, { kind: "editorial-split", theme: "paper", id: "erp-finance" }, { kind: "workflow", theme: "white", id: "erp-source" }, { kind: "feature-ledger", theme: "navy", id: "erp-features" }, { kind: "ai-layer", theme: "blue", id: "erp-ai" }, { kind: "faq", theme: "white", id: "erp-faq" }, { kind: "conversion", theme: "paper", id: "erp-cta" }],
  }),
  product({
    slug: "protect",
    name: "Sidekick Protect",
    category: "Protection",
    tagline: "Know what is protected and prove it can recover.",
    hero: { eyebrow: "Sidekick Protect", title: "Protection is only useful when recovery is clear.", body: "Cover workstations, servers, and cloud users with policy, monitoring, retention, alerts, and recovery status connected to your Sidekick account." },
    seo: { title: "Sidekick Protect | Workstation, server, and cloud backup protection", description: "Protect workstations, servers, and cloud users with policy-based backup, monitoring, retention, alerts, and recovery workflows." },
    outcomes: ["A visible coverage inventory", "Actionable backup and protection alerts", "Recovery status the business can understand"],
    featureGroups: [
      { title: "Coverage by workload", description: "Select the systems and users that need protection without buying an opaque bundle.", features: ["Workstation protection", "Physical and virtual server protection", "Cloud productivity user protection", "Storage and retention controls"] },
      { title: "Operational recovery", description: "See policy, health, failure, and restore context in one place.", features: ["Policy deployment and status", "Backup health and alerting", "Ransomware resilience controls", "Restore requests and recovery evidence"] },
    ],
    workflows: [
      { title: "Add a newly critical server", description: "Select coverage, deploy policy, confirm the first protected state, and keep readiness visible.", steps: ["Identify the workload", "Select coverage", "Deploy protection", "Verify backup and recovery status"] },
      { title: "Respond to a failed protection signal", description: "Sidekick turns a signal into accountable service work with the affected record attached.", steps: ["Receive the alert", "Resolve workload and owner", "Remediate or escalate", "Confirm protected state"] },
    ],
    relevantIndustries: ["law-firms", "financial-services", "managed-service-providers", "medical-clinics"],
    faqs: [
      { question: "Is there a free trial?", answer: "No. Sidekick Protect begins as a paid service because onboarding creates real workload coverage and provider commitments." },
      { question: "How is it priced?", answer: "Pricing is transparent per protected workstation, server, or cloud user, with metered storage overage where applicable." },
    ],
    pricingOfferKeys: ["protect.workstation", "protect.server", "protect.cloud-user"],
    cta: { label: "Configure protection", href: "/checkout?offer=protect.workstation", trialEligible: false },
    media: media("protect", "product-ui", "Sidekick Protect coverage and recovery readiness workspace", "Show coverage, health, retention, and recovery evidence without provider branding or fear imagery."),
    slices: [{ kind: "hero", theme: "navy", id: "protect-hero" }, { kind: "workflow", theme: "paper", id: "protect-coverage" }, { kind: "media-stage", theme: "white", id: "protect-readiness" }, { kind: "feature-ledger", theme: "navy", id: "protect-features" }, { kind: "faq", theme: "white", id: "protect-faq" }, { kind: "conversion", theme: "blue", id: "protect-cta" }],
  }),
  product({
    slug: "commerce",
    name: "Sidekick Commerce",
    category: "Money and commerce",
    tagline: "Sell across channels without splitting inventory or customers.",
    hero: { eyebrow: "Sidekick Commerce", title: "One product, one customer, every place you sell.", body: "Manage products, variants, price lists, inventory, carts, orders, shipping, POS, promotions, returns, and payments on the same platform." },
    seo: { title: "Sidekick Commerce | Connected online store, POS, orders, and inventory", description: "Run products, variants, price lists, inventory, online checkout, orders, POS, shipping, returns, and customer records together." },
    outcomes: ["One catalogue across online and in person", "Inventory that follows the order", "Customer context after checkout"],
    featureGroups: [
      { title: "Merchandise and sell", description: "Create a clear catalogue and make it available in the right channel and market.", features: ["Products, variants, collections, and media", "Price lists, promotions, and market rules", "Online cart and checkout", "POS and in-person selling"] },
      { title: "Fulfil and keep the relationship", description: "Connect the order to stock, delivery, payment, return, and customer follow-up.", features: ["Inventory and multi-location availability", "Orders, shipping, pickup, and delivery", "Returns, refunds, and exchanges", "CRM, Payments, Sites, and reporting"] },
    ],
    workflows: [
      { title: "Online order to local fulfilment", description: "Sidekick selects inventory, coordinates pickup or shipment, and keeps the customer informed.", steps: ["Accept checkout", "Reserve available stock", "Pick and fulfil", "Update customer and financial records"] },
      { title: "In-store sale with a known customer", description: "The point of sale recognizes the customer, pricing, inventory, and payment without a second database.", steps: ["Find product and customer", "Apply the right price", "Take terminal payment", "Update inventory and history"] },
    ],
    relevantIndustries: ["retail", "restaurants-and-food-service", "wholesale-distribution", "franchises-and-multi-location"],
    faqs: [
      { question: "Does Commerce include payment processing?", answer: "Commerce connects directly to Sidekick Payments. Processing and physical terminals are configured and priced separately." },
      { question: "Can inventory span multiple locations?", answer: "Professional and Enterprise support deeper multi-location workflows and controls according to the published edition." },
    ],
    pricingOfferKeys: ["commerce.essentials", "commerce.professional", "commerce.enterprise"],
    cta: { label: "Start a 30-day Commerce trial", href: "/checkout?offer=commerce.essentials", trialEligible: true },
    media: media("commerce", "product-ui", "Sidekick Commerce product, order, inventory, and POS workspace", "Combine product storytelling with concrete order and stock states; avoid generic storefront mockups."),
    slices: [{ kind: "hero", theme: "navy", id: "commerce-hero" }, { kind: "media-stage", theme: "white", id: "commerce-catalogue" }, { kind: "workflow", theme: "paper", id: "commerce-order" }, { kind: "feature-ledger", theme: "navy", id: "commerce-features" }, { kind: "edition-comparison", theme: "white", id: "commerce-editions" }, { kind: "faq", theme: "paper", id: "commerce-faq" }, { kind: "conversion", theme: "blue", id: "commerce-cta" }],
  }),
  product({
    slug: "appointments",
    name: "Sidekick Appointments",
    category: "Service operations",
    tagline: "Make it easy to book and easier to run the day.",
    hero: { eyebrow: "Sidekick Appointments", title: "Turn open time into confirmed, prepared appointments.", body: "Publish services, coordinate staff calendars, take deposits, send reminders, manage intake and waitlists, and keep every visit connected to the customer." },
    seo: { title: "Sidekick Appointments | Online booking for service businesses", description: "Manage services, staff calendars, online booking, reminders, deposits, intake, waitlists, recurring appointments, and customer history." },
    outcomes: ["More self-serve bookings", "Fewer gaps and missed appointments", "Staff start with the right customer context"],
    featureGroups: [
      { title: "A booking experience customers finish", description: "Make service, staff, location, availability, and policies easy to understand.", features: ["Online service catalogue and booking", "Staff and resource calendars", "Deposits, cancellation rules, and payment", "Reminders, confirmations, and rescheduling"] },
      { title: "A prepared service day", description: "Help the team see who is coming, what they need, and what should happen next.", features: ["Customer history and notes", "Intake forms and preferences", "Waitlists and recurring appointments", "Utilization, revenue, and follow-up reports"] },
    ],
    workflows: [
      { title: "A client books after hours", description: "The customer chooses a service and time, pays the required deposit, and receives the right preparation details.", steps: ["Choose service and staff", "Confirm available time", "Complete intake and deposit", "Send confirmation and reminders"] },
      { title: "A cancellation fills itself", description: "Sidekick applies policy, alerts the waitlist, and offers the opening without a phone tree.", steps: ["Receive cancellation", "Apply the policy", "Offer the time to the waitlist", "Confirm the replacement booking"] },
    ],
    relevantIndustries: ["beauty-salons-and-spas", "fitness-and-wellness", "medical-clinics", "veterinary-and-pet-services"],
    faqs: [
      { question: "Can each staff member have a calendar?", answer: "Yes. Availability can account for staff, services, locations, resources, time off, and booking rules." },
      { question: "Can we require deposits?", answer: "Yes. Connect Sidekick Payments to collect deposits and enforce cancellation policies during booking." },
    ],
    pricingOfferKeys: ["appointments.essentials", "appointments.professional", "appointments.enterprise"],
    cta: { label: "Start a 30-day Appointments trial", href: "/checkout?offer=appointments.essentials", trialEligible: true },
    media: media("appointments", "product-ui", "Sidekick Appointments staff calendar, online booking, and customer preparation view", "Use service-business photography beside a legible daily schedule and booking details."),
    slices: [{ kind: "hero", theme: "navy", id: "appointments-hero" }, { kind: "editorial-split", theme: "paper", id: "appointments-booking" }, { kind: "workflow", theme: "white", id: "appointments-waitlist" }, { kind: "feature-ledger", theme: "navy", id: "appointments-features" }, { kind: "edition-comparison", theme: "white", id: "appointments-editions" }, { kind: "faq", theme: "paper", id: "appointments-faq" }, { kind: "conversion", theme: "blue", id: "appointments-cta" }],
  }),
  product({
    slug: "sites",
    name: "Sidekick Sites",
    category: "Customer growth",
    tagline: "Publish the front door to the business you already run.",
    hero: { eyebrow: "Sidekick Sites", title: "A website that knows what happens after the form is sent.", body: "Build, publish, connect domains, manage content, capture leads, book services, sell products, and measure results without losing the customer handoff." },
    seo: { title: "Sidekick Sites | Connected business website builder", description: "Create and publish a professional website with domains, SEO, forms, analytics, commerce, booking, and Sidekick customer workflows." },
    outcomes: ["A professional site without a disconnected stack", "Forms and bookings become real customer records", "Pages can reflect products and operations already in Sidekick"],
    featureGroups: [
      { title: "Build and publish", description: "Create an intentional site with reusable content and professional publishing controls.", features: ["AI-assisted starting points and themes", "Structured sections and content", "Custom domains and secure hosting", "SEO, metadata, redirects, and analytics"] },
      { title: "Connect the next action", description: "Turn attention into a trackable customer workflow.", features: ["CRM-connected forms", "Appointments and service booking", "Commerce and product catalogue", "Campaign, attribution, and conversion context"] },
    ],
    workflows: [
      { title: "Launch a service page from the operating record", description: "Use approved service information, publish the page, and route inquiries into the right team workflow.", steps: ["Choose the service record", "Compose the page", "Connect form or booking", "Publish and measure"] },
      { title: "A web inquiry becomes accountable", description: "Sidekick creates or matches the customer and assigns the right next action with source context.", steps: ["Capture the form", "Match customer and campaign", "Assign owner and task", "Track conversion"] },
    ],
    relevantIndustries: ["professional-services", "home-services", "beauty-salons-and-spas", "technology-and-saas"],
    faqs: [
      { question: "Can we use our own domain?", answer: "Yes. Connect a domain you own or purchase one through the supported domain workflow once configured." },
      { question: "Does Sites include Commerce or Appointments?", answer: "Sites connects to those products, but their operational capabilities and pricing remain separate." },
    ],
    pricingOfferKeys: ["sites.essentials", "sites.professional", "sites.enterprise"],
    cta: { label: "Start a 30-day Sites trial", href: "/checkout?offer=sites.essentials", trialEligible: true },
    media: media("sites", "product-ui", "Sidekick Sites page editor connected to customer forms and publishing status", "Show a polished real editor and published result rather than a floating browser-card collage."),
    slices: [{ kind: "hero", theme: "navy", id: "sites-hero" }, { kind: "media-stage", theme: "paper", id: "sites-builder" }, { kind: "workflow", theme: "white", id: "sites-handoff" }, { kind: "feature-ledger", theme: "navy", id: "sites-features" }, { kind: "edition-comparison", theme: "white", id: "sites-editions" }, { kind: "faq", theme: "paper", id: "sites-faq" }, { kind: "conversion", theme: "blue", id: "sites-cta" }],
  }),
  product({
    slug: "desktop",
    name: "Sidekick Desktop",
    category: "Platform",
    tagline: "Keep the work close without living in a browser tab.",
    hero: { eyebrow: "Sidekick Desktop", title: "Calling, alerts, and the next customer action—right on the desktop.", body: "Bring Sidekick calling, notifications, shortcuts, and deep links into a secure desktop companion that stays connected to the workspace." },
    seo: { title: "Sidekick Desktop | Native calling and workspace companion", description: "Use Sidekick calling, notifications, shortcuts, deep links, and secure updates from a native desktop companion included with paid access." },
    outcomes: ["Answer calls without hunting for a tab", "Open the right Sidekick record from a notification", "Keep desktop updates secure and automatic"],
    featureGroups: [
      { title: "Work at the edge of the workspace", description: "Keep high-frequency actions available while using other applications.", features: ["Native Sidekick Voice calling", "Actionable notifications", "Global shortcuts", "Deep links into customer and work records"] },
      { title: "Managed continuity", description: "Preserve identity and update state across the native and web experience.", features: ["Secure authentication handoff", "Workspace continuity", "Automatic signed updates", "Device and session controls"] },
    ],
    workflows: [
      { title: "Answer with customer context", description: "A desktop call notification opens the matched customer record without breaking the conversation.", steps: ["Receive the call", "Resolve caller context", "Open the Sidekick record", "Capture follow-up"] },
      { title: "Move from alert to action", description: "A useful notification links directly to the specific record and task that needs attention.", steps: ["Receive priority alert", "Review concise context", "Open the target record", "Complete or assign action"] },
    ],
    relevantIndustries: ["managed-service-providers", "professional-services", "internal-service-desks", "staffing-and-recruiting"],
    faqs: [
      { question: "Is Sidekick Desktop sold separately?", answer: "No. It is included with every paid Sidekick user entitlement." },
      { question: "Does it replace the web app?", answer: "No. It keeps calling and high-frequency actions close while deep-linking into the full Sidekick workspace." },
    ],
    pricingOfferKeys: [],
    cta: { label: "Explore the Sidekick platform", href: "/platform", trialEligible: true },
    media: media("desktop", "product-ui", "Sidekick Desktop call and notification companion beside the connected workspace", "Use a grounded desktop composition with the native call surface and exact deep-linked record."),
    slices: [{ kind: "hero", theme: "navy", id: "desktop-hero" }, { kind: "media-stage", theme: "paper", id: "desktop-calling" }, { kind: "workflow", theme: "white", id: "desktop-action" }, { kind: "feature-ledger", theme: "navy", id: "desktop-features" }, { kind: "faq", theme: "paper", id: "desktop-faq" }, { kind: "conversion", theme: "blue", id: "desktop-cta" }],
  }),
  product({
    slug: "ai",
    name: "Sidekick AI",
    category: "Platform",
    tagline: "AI that can see the work and help move it forward.",
    hero: { eyebrow: "Sidekick AI", title: "Useful intelligence inside the record—not a chatbot beside it.", body: "Summarize context, prepare decisions, recommend actions, and deploy governed AI Agents that work across the Sidekick products your team uses." },
    seo: { title: "Sidekick AI | Embedded intelligence and configurable AI Agents", description: "Use embedded AI across Sidekick and deploy separately purchased, governed AI Agents with transparent credit-based usage." },
    outcomes: ["Less time assembling context", "Recommendations grounded in business records", "Automated work with visible controls and usage"],
    featureGroups: [
      { title: "Embedded where decisions happen", description: "Each eligible product contributes purpose-built intelligence rather than a generic chat layer.", features: ["Record and timeline summaries", "Drafts, recommendations, and next actions", "Forecast, exception, and knowledge signals", "Tier-aware limits and governance"] },
      { title: "Agents for repeatable work", description: "Configure separately purchased agents with explicit tools, permissions, and metered credits.", features: ["Agent roles and instructions", "Approved cross-product tools", "Versioned credit consumption", "Audit, controls, and human handoff"] },
    ],
    workflows: [
      { title: "Prepare the next best customer action", description: "Sidekick assembles the relationship, open work, communication, and commercial context into a reviewable recommendation.", steps: ["Resolve the customer", "Gather relevant records", "Explain the recommendation", "Let the user approve or adjust"] },
      { title: "An agent completes a governed workflow", description: "A configured agent uses only allowed tools, records each action, and hands off when policy requires it.", steps: ["Receive a trigger", "Evaluate policy and context", "Perform approved actions", "Record outcome and usage"] },
    ],
    relevantIndustries: ["technology-and-saas", "managed-service-providers", "professional-services", "multi-entity-operators"],
    faqs: [
      { question: "Is Sidekick AI included?", answer: "Embedded AI is included according to product edition limits. Configured AI Agents are separate recurring offers with metered credits." },
      { question: "Does Voice AI use the same credits?", answer: "No. Voice AI remains part of Sidekick Voice and does not consume general Sidekick AI Agent credits." },
    ],
    pricingOfferKeys: ["ai.agent", "ai.credits.10000"],
    cta: { label: "Configure a Sidekick AI Agent", href: "/checkout?offer=ai.agent", trialEligible: true },
    media: media("ai", "product-ui", "Sidekick AI recommendation and agent activity grounded in customer and operational records", "Show an auditable work timeline with sources, tools, approval, and outcome—no abstract node-cloud graphic."),
    slices: [{ kind: "hero", theme: "navy", id: "ai-hero" }, { kind: "ai-layer", theme: "paper", id: "ai-embedded" }, { kind: "workflow", theme: "white", id: "ai-agent" }, { kind: "feature-ledger", theme: "navy", id: "ai-governance" }, { kind: "editorial-split", theme: "blue", id: "ai-credits" }, { kind: "faq", theme: "white", id: "ai-faq" }, { kind: "conversion", theme: "paper", id: "ai-cta" }],
  }),
] as const;

export const getProduct = (slug: string) =>
  PRODUCTS.find((candidate) => candidate.slug === slug);
